using System;
using System.Collections.Generic;
using UnityEngine.UIElements;

public static class AllItemData
{
    public static List<ItemData> itemDatas = new List<ItemData>{
        new ItemData{
            id = 0,
            nextLevel = 1,
            row = 2,
            column = 1,
            name = "ปืนเล็ก",
            spriteName = "QuickAttack_LV1",
            minDamage = 1,
            maxDamage = 3,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 1,
            cooldown = 1.4f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 1,
            nextLevel = 2,
            row = 3,
            column = 2,
            name = "ปืนกลาง",
            spriteName = "QuickAttack_LV2",
            minDamage = 2,
            maxDamage = 4,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 1.2f,
            cooldown = 1.2f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 2,
            nextLevel = -1,
            row = 3,
            column = 2,
            name = "ปืนคนจีน",
            spriteName = "QuickAttack_LV3",
            minDamage = 2,
            maxDamage = 4,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 1,
            cooldown = 0.8f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 3,
            nextLevel = 4,
            row = 3,
            column = 1,
            name = "ปืนไทประดิษฐ์",
            spriteName = "NormalAttack_LV1",
            minDamage = 1,
            maxDamage = 4,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 1.7f,
            cooldown = 1.8f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 4,
            nextLevel = 5,
            row = 3,
            column = 2,
            name = "ปืนลากหัว",
            spriteName = "NormalAttack_LV2",
            minDamage = 2,
            maxDamage = 5,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 2.2f,
            cooldown = 2f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 5,
            nextLevel = -1,
            row = 3,
            column = 2,
            name = "ปืนทะลวงสวรรค์",
            spriteName = "NormalAttack_LV3",
            minDamage = 4,
            maxDamage = 7,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 2.2f,
            cooldown = 2.2f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 6,
            nextLevel = 7,
            row = 2,
            column = 1,
            name = "ขันตีหัว",
            spriteName = "PowerAttack_LV1",
            minDamage = 3,
            maxDamage = 5,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 2f,
            cooldown = 2f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 7,
            nextLevel = 8,
            row = 2,
            column = 2,
            name = "ขันลอย",
            spriteName = "PowerAttack_LV2",
            minDamage = 4,
            maxDamage = 6,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 2.7f,
            cooldown = 2.4f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 8,
            nextLevel = -1,
            row = 3,
            column = 3,
            name = "ถังรถล้ม",
            spriteName = "PowerAttack_LV3",
            minDamage = 4,
            maxDamage = 8,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 3f,
            cooldown = 2.7f,
            itemType = ItemType.ATTACK
        },
        new ItemData{
            id = 9,
            nextLevel = 10,
            row = 3,
            column = 3,
            name = "ชุดช้าง",
            spriteName = "Defense_LV1",
            minDamage = 0,
            maxDamage = 0,
            block = 8,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 0,
            cooldown = 0,
            itemType = ItemType.DEFENSE
        },
        new ItemData{
            id = 10,
            nextLevel = 11,
            row = 3,
            column = 3,
            name = "ชุดฮาวาย",
            spriteName = "Defense_LV2",
            minDamage = 0,
            maxDamage = 0,
            block = 12,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 0,
            cooldown = 0,
            itemType = ItemType.DEFENSE
        },
        new ItemData{
            id = 11,
            nextLevel = -1,
            row = 3,
            column = 4,
            name = "ชุดไทย",
            spriteName = "Defense_LV3",
            minDamage = 0,
            maxDamage = 0,
            block = 0,
            regenHp = 0,
            regenStamina = 0,
            staminaCost = 0,
            cooldown = 0,
            itemType = ItemType.DEFENSE
        },
        new ItemData{
            id = 12,
            nextLevel = 13,
            row = 1,
            column = 3,
            name = "ไก่ย่าง",
            spriteName = "HP_LV1",
            minDamage = 0,
            maxDamage = 0,
            block = 0,
            regenHp = 2,
            regenStamina = 0,
            staminaCost = 0,
            cooldown = 4f,
            itemType = ItemType.SUPPORT
        },
        new ItemData{
            id = 13,
            nextLevel = 14,
            row = 2,
            column = 2,
            name = "ส้มตำไม่พริก",
            spriteName = "HP_LV2",
            minDamage = 0,
            maxDamage = 0,
            block = 0,
            regenHp = 2,
            regenStamina = 0,
            staminaCost = 0,
            cooldown = 3f,
            itemType = ItemType.SUPPORT
        },
        new ItemData{
            id = 14,
            nextLevel = -1,
            row = 2,
            column = 3,
            name = "อาหารเจ้าสัว",
            spriteName = "HP_LV3",
            minDamage = 0,
            maxDamage = 0,
            block = 0,
            regenHp = 3.5f,
            regenStamina = 0,
            staminaCost = 0,
            cooldown = 3f,
            itemType = ItemType.SUPPORT
        },
        new ItemData{
            id = 15,
            nextLevel = 16,
            row = 1,
            column = 2,
            name = "เบียร์บิน",
            spriteName = "Stamina_LV1",
            minDamage = 0,
            maxDamage = 0,
            block = 0,
            regenHp = 0,
            regenStamina = 2,
            staminaCost = 0,
            cooldown = 3f,
            itemType = ItemType.SUPPORT
        },
        new ItemData{
            id = 16,
            nextLevel = 17,
            row = 1,
            column = 3,
            name = "อาวุธฉุกเฉิน",
            spriteName = "Stamina_LV2",
            minDamage = 0,
            maxDamage = 0,
            block = 0,
            regenHp = 0,
            regenStamina = 2.5f,
            staminaCost = 0,
            cooldown = 4f,
            itemType = ItemType.SUPPORT
        },
        new ItemData{
            id = 17,
            nextLevel = -1,
            row = 1,
            column = 3,
            name = "น้ำเปล่าคนอีสาน",
            spriteName = "Stamina_LV3",
            minDamage = 0,
            maxDamage = 0,
            block = 0,
            regenHp = 0,
            regenStamina = 3,
            staminaCost = 0,
            cooldown = 4.5f,
            itemType = ItemType.SUPPORT
        },
    };
}
